name: trophies_zone
description: A new Flutter project.

version: 1.0.0+1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^2.3.1
  convex_bottom_bar: ^3.0.0
  accordion: ^2.2.3
  fl_chart: ^0.50.1
  webview_flutter: ^3.0.2
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
